// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OmniDestinyTierInput = { saju: any, vedic: any, western: any, zwds: any, humanDesign: any, qimen: any, numerology: any, transit: any, };
