// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuantumSynergyItem = { title: string, engines: Array<string>, scoreDelta: number, isPositive: boolean, description: string, };
