// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServiceError = { "type": "invalidInput", "message": string } | { "type": "birthInfo", "message": string } | { "type": "saju", "message": string } | { "type": "vedic", "message": string } | { "type": "transit", "message": string } | { "type": "compatibility", "message": string } | { "type": "aiAudit", "message": string } | { "type": "serialization", "message": string };
