// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DestinyComponent } from "./DestinyComponent";
import type { DomainTier } from "./DomainTier";
import type { ScoreResult } from "./ScoreResult";
import type { TierGrade } from "./TierGrade";

export type TierResult = { natalScore: number, currentScore: number, destinyScore: number, destinyTier: TierGrade, potentialScore: number, potentialTier: TierGrade, domainTiers: Array<DomainTier>, sajuResult: ScoreResult, vedicResult: ScoreResult, transitResult: ScoreResult, strengths: Array<string>, weaknesses: Array<string>, growthGap: number, riskLevel: string, profile: string, version: string, destinyRawScore: number, destinyTierScore: number, detailedComponents: Array<DestinyComponent>, tierModelVersion: string, };
