[application]
name = "eon-ui"
default_platform = "web"
asset_dir = "public"

[web.app]
title = "Eon: Destiny Engine"

[web.resource]
style = ["tailwind.css"]
script = []

[web.resource.dev]
style = ["tailwind.css"]
script = []
