pub fn get_nakshatra_name(index: u8) -> &'static str {
    match index {
        1 => "Ashwini",
        2 => "Bharani",
        3 => "Krittika",
        4 => "Rohini",
        5 => "Mrigashirsha",
        6 => "Ardra",
        7 => "Punarvasu",
        8 => "Pushya",
        9 => "Ashlesha",
        10 => "Magha",
        11 => "Purva Phalguni",
        12 => "Uttara Phalguni",
        13 => "Hasta",
        14 => "Chitra",
        15 => "Swati",
        16 => "Vishakha",
        17 => "Anuradha",
        18 => "Jyeshtha",
        19 => "Mula",
        20 => "Purva Ashadha",
        21 => "Uttara Ashadha",
        22 => "Shravana",
        23 => "Dhanishta",
        24 => "Shatabhisha",
        25 => "Purva Bhadrapada",
        26 => "Uttara Bhadrapada",
        27 => "Revati",
        _ => "Unknown",
    }
}

pub fn get_rasi_name(index: u8) -> &'static str {
    match index {
        1 => "Aries",
        2 => "Taurus",
        3 => "Gemini",
        4 => "Cancer",
        5 => "Leo",
        6 => "Virgo",
        7 => "Libra",
        8 => "Scorpio",
        9 => "Sagittarius",
        10 => "Capricorn",
        11 => "Aquarius",
        12 => "Pisces",
        _ => "Unknown",
    }
}
