name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Cache Rust dependencies
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install Dioxus CLI
        run: cargo binstall dioxus-cli@0.6.1 -y

      - name: Install WASI SDK
        run: |
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-24/wasi-sdk-24.0-x86_64-linux.tar.gz
          sudo tar xf wasi-sdk-24.0-x86_64-linux.tar.gz -C /opt
          sudo ln -s /opt/wasi-sdk-24.0-x86_64-linux /opt/wasi-sdk

      - name: Build Rust Wasm Explicitly (For Debugging Cargo Error)
        working-directory: ./crates/eon-ui
        env:
          CARGO_BUILD_JOBS: 1
          CC_wasm32_unknown_unknown: clang
          AR_wasm32_unknown_unknown: llvm-ar
          WASI_SDK_PATH: /opt/wasi-sdk
        run: cargo build --target wasm32-unknown-unknown --release

      - name: Build Dioxus Web App
        working-directory: ./crates/eon-ui
        env:
          CARGO_BUILD_JOBS: 1
        run: dx build --release --trace

      - name: Inject Assets (Post-Build)
        working-directory: ./crates/eon-ui
        run: |
          cp ./public/vercel.json ../../target/dx/eon-ui/release/web/public/
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.17/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          ./tailwindcss-linux-x64 -i ./input.css -o ../../target/dx/eon-ui/release/web/public/tailwind.css --minify
          rm tailwindcss-linux-x64

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v42
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./target/dx/eon-ui/release/web/public
          vercel-args: '--prod'
